### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by yzho0907** [CrisJk/Agriculture-KnowledgeGraph-Data#1]
when i was running scrapy crawl entityRelation but the code below throw an error:

File "/home/young/Downloads/Agriculture-KnowledgeGraph-Data-master/wikidataRelation/wikidataRelation/spiders/getEntityRelation.py", line 34, in parse
    relation = relationJson['rmention']

any idea how to fix it??

**Comment by JunKuang-algo** [comment]
Sorry for my late reply! You can check if it exists file "relationResult.json" at "home/young/Downloads/Agriculture-KnowledgeGraph-Data-master/wikidataRelation". Or you probably should run "scrapy crawl entityRelation" at the directory "home/young/Downloads/Agriculture-KnowledgeGraph-Data-master/wikidataRelation".
